# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teste_gazebo_launcher.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(648, 460)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 681, 491))
        self.frame.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(200, 310, 461, 71))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    color: black;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(52, 101, 164);\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(32, 74, 135);\n"
"    color: white;\n"
"\n"
"}\n"
"  ")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 390, 461, 71))
        self.pushButton_2.setStyleSheet("QPushButton{    \n"
"    background-color: rgb(255, 255, 255);\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{    \n"
"    background-color: rgb(52, 101, 164);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(32, 74, 135);\n"
"    color: white;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 0, 191, 461))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../arquivos_mestrado/modelo_braço_robótico.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(200, 0, 461, 111))
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 190, 131, 71))
        self.pushButton_3.setStyleSheet("QPushButton{    \n"
"    \n"
"    \n"
"    background-color: rgb(239, 41, 41);\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover{    \n"
"    \n"
"    background-color: rgb(204, 0, 0);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(164, 0, 0);\n"
"    color: white;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(310, 160, 231, 20))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Start Gazebo"))
        self.pushButton_2.setText(_translate("Form", "End Gazebo"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Robotic Arm Module (Gazebo-ROS2)</span></p></body></html>"))
        self.pushButton_3.setText(_translate("Form", "Exit"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">Always Close the App Here</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
