# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_angles.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 238)
        Form.setStyleSheet("background-color: rgb(32, 74, 135);")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 20, 381, 211))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("background-color: rgb(64, 173, 191);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.elbow_angle_label = QtWidgets.QLabel(self.widget)
        self.elbow_angle_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.elbow_angle_label.setText("")
        self.elbow_angle_label.setObjectName("elbow_angle_label")
        self.horizontalLayout.addWidget(self.elbow_angle_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setStyleSheet("background-color: rgb(64, 173, 191);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.elbow_angle_to_reach_label = QtWidgets.QLabel(self.widget)
        self.elbow_angle_to_reach_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.elbow_angle_to_reach_label.setText("")
        self.elbow_angle_to_reach_label.setObjectName("elbow_angle_to_reach_label")
        self.horizontalLayout_3.addWidget(self.elbow_angle_to_reach_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setStyleSheet("background-color: rgb(64, 173, 191);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.shoulder_angle_label = QtWidgets.QLabel(self.widget)
        self.shoulder_angle_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.shoulder_angle_label.setText("")
        self.shoulder_angle_label.setObjectName("shoulder_angle_label")
        self.horizontalLayout_4.addWidget(self.shoulder_angle_label)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setStyleSheet("background-color: rgb(64, 173, 191);")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.shoulder_angle_to_reach_angle = QtWidgets.QLabel(self.widget)
        self.shoulder_angle_to_reach_angle.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.shoulder_angle_to_reach_angle.setText("")
        self.shoulder_angle_to_reach_angle.setObjectName("shoulder_angle_to_reach_angle")
        self.horizontalLayout_5.addWidget(self.shoulder_angle_to_reach_angle)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Elbow Angle</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Elbow Angle to reach</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Shoulder Angle</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Shoulder Angle to Reach</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
